apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        #image: gcr.io/google_containers/volume-nfs:0.8
        image: europe-west8-docker.pkg.dev/orthogether-1483375746166/otg-registry/nfs-server:8
        securityContext:
          privileged: true # Container context
        env:
        - name: EXPORTS
          value: "/exports *(rw,fsid=0,sync,no_subtree_check,no_root_squash)"
        ports:
        - containerPort: 2049
        - containerPort: 20048
        - containerPort: 111
          protocol: UDP
        - containerPort: 111
          protocol: TCP
        volumeMounts:
          - mountPath: /exports
            name: nfs-pvc
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: storage-volume
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind-udp
      port: 111
      protocol: UDP
    - name: rpcbind-tcp
      port: 111
      protocol: TCP
  selector:
    role: nfs-server

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
spec:
  storageClassName: "standard-rwo"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name:  storage-volume
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/PROJECT/zones/ZONE/disks/storage-volume   # path of volume on GKE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi  # size of you volume
  storageClassName: standard-rwo
---    